# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmistan', '0002_auto_20160516_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
