# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmistan', '0003_film_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.FloatField(default='0'),
        ),
    ]
